### ISSUE TITLE
Game crashes on player death and loss of all items when using You're in grave danger, worked in Traveler's Backpack 1.21.1-10.1.3

### ISSUE THREAD

**Issue by quaap** [Tiviacz1337/Travelers-Backpack#1111]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

Game crashes on player death when using You're in grave danger. This results in loss of all items.

This worked in Traveler's Backpack 1.21.1-10.1.3. 

Crash report shows java.lang.NoSuchMethodError: 'com.tiviacz.travelersbackpack.component.ITravelersBackpackComponent'

Using:
Minecraft 1.21.1
Fabric 0.16.9
You're in grave danger 2.4.11
Traveler's backpack 1.21.1-10.1.4+

2. Write steps to reproduce the bug

Create world with
Minecraft 1.21.1
Fabric 0.16.9
You're in grave danger 2.4.11
Traveler's backpack 1.21.1-10.1.4+

Do a '/kill'

3. What is expected behaviour 

No crash, items preserved.

[crash-2025-01-03_15.01.00-server.txt](https://github.com/user-attachments/files/18303945/crash-2025-01-03_15.01.00-server.txt)

**Comment by quaap** [comment]
Here is a mrpack testcase
[issue1111-testcase 1.0.0.mrpack.zip](https://github.com/user-attachments/files/18303989/issue1111-testcase.1.0.0.mrpack.zip)

**Comment by Tiviacz1337** [comment]
We have to wait for Yigd update

**Comment by Tiviacz1337** [comment]
Travelers Backpack received inventory and most logic rewrite so some graves mods that add compat on their own have to adapt to changes

**Comment by quaap** [comment]
Ah, makes sense

**Comment by Tiviacz1337** [comment]
Fixed
https://github.com/B1n-ry/Youre-in-grave-danger/issues/196
